<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class QrCode extends Model
{
    use HasFactory;
    protected $fillable = [
        'user_id', 'vendor_id', 'qr_code', 'amount', 'status',
    ];

    // A QR code belongs to a user (if generated by a user)
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    // A QR code belongs to a vendor (if generated by a vendor)
    public function vendor()
    {
        return $this->belongsTo(Vendor::class);
    }
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d M Y, h:i A'); 
    }
        
    public function getUpdatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('d M Y, h:i A'); 
    }
}
